[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput --no-input"]

[start]
cmd = "gunicorn FashioHub.wsgi:application --bind 0.0.0.0:$PORT"
