services:
  - type: web
    name: fashionhub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn FashioHub.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fashionhub-db
          property: connectionString

databases:
  - name: fashionhub-db
    databaseName: fashionhub
    user: fashionhub
