services:
  - type: web
    name: fashionhub
    env: python
    region: singapore
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn FashioHub.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.7
